modified reset() for I2C sharing with other sensors
adafruit/Adafruit_MAX1704X pull request #4
Opened 2023-09-11 21:37 UTC by mikeysklar

reset() driver code provided by @caternusen. Tested on ESP32-S3 Rev TFT with SHT41. Code compiled and ran without any timeout or error messages. Previous releases were not allowing the MAX17048  to initialize with SHTXX temperature sensors or SGP40 gas sensors (probably others too).

2023-09-12 00:58 UTC, caternuson commented
CI fail is some kind of temporary network issue with the [megatinycore BSP URL](https://github.com/SpenceKonde/megaTinyCore/blob/master/Installation.md#boards-manager-installation-now-strongly-recommended-unless-helping-with-core-development):
```
http://drazzy.com/package_drazzy.com_index.json
```

Related issue here:
https://github.com/SpenceKonde/megaTinyCore/issues/1001

2023-09-12 13:59 UTC, mikeysklar commented
I've been struggling trying to figure out how to re-run the failed PR. Is there something I need to do to retry? The git docs are a little dated on where things are located.

2023-09-12 14:06 UTC, dhalbert commented
> I've been struggling trying to figure out how to re-run the failed PR. Is there something I need to do to retry? The git docs are a little dated on where things are located.

Do you have this button?

![image](https://github.com/adafruit/Adafruit_MAX1704X/assets/2847802/6859d979-97af-4226-a132-6073a9820692)

2023-09-12 14:18 UTC, mikeysklar commented
No, and that is the one I have been looking for. 
![Screenshot from 2023-09-12 07-16-52](https://github.com/adafruit/Adafruit_MAX1704X/assets/1987700/9a150bde-7e38-4631-87d5-46e1ecc93949)

2023-09-12 14:25 UTC, dhalbert commented
Click here to get to what my screenshot shows:
![image](https://github.com/adafruit/Adafruit_MAX1704X/assets/2847802/c5f17349-0879-4c6c-a516-de2af6373eda)

2023-09-12 15:03 UTC, mikeysklar commented
Sorry, wrong tab screenshot, but same issue for me. 

<img width="1144" alt="Screenshot 2023-09-12 at 8 02 01 AM" src="https://github.com/adafruit/Adafruit_MAX1704X/assets/1987700/dab6690d-c9a9-4d62-a2d2-4f024e18bc9d">

2023-09-12 15:07 UTC, caternuson commented
The re-run option not being visible would be a permissions issue. But also, re-running won't help until the underlying issue (see link above) is resolved.

2023-09-12 15:31 UTC, mikeysklar commented
Thank you @caternuson. I see drazzy.com domain is still unavailable and a permission issue would make sense.

2023-09-12 17:20 UTC, caternuson commented
The issue has been temporarily fixed (offending URL removed). Re-ran the CI and it's now failing on clang formatting.

2023-09-12 17:22 UTC, caternuson requested changes

2023-09-12 17:22 UTC, caternuson commented on Adafruit_MAX1704X.cpp
> +  // the actual reset, this should *fail*
This comment is potentially confusing. Maybe?
```cpp
// send reset command, the MAX1704 will reset before ACKing, so I2C xfer is expected to *fail* with a NACK
```

2023-09-12 19:27 UTC, mikeysklar commented on Adafruit_MAX1704X.cpp
> +  // the actual reset, this should *fail*
updated along with a few other comment / whitespace modifications to appease the check-in script gods.

2023-09-17 13:51 UTC, mikeysklar commented
@caternuson - Can you commit this PR for me? I don't have the permissions.

2023-09-17 14:44 UTC, caternuson approved these changes

2023-09-17 14:44 UTC, caternuson commented on Adafruit_MAX1704X.cpp
> +    // add retry delay?
Let's remove this comment if delay is not needed.

2023-09-17 14:44 UTC, merged